# -*- coding: utf-8 -*-
"""Shipgui.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UeckRiUr2JjtmH1RVLaMJGDiIbVOpUUf
"""

import pandas as pd
import folium
import io
import webbrowser
from folium.plugins import MousePosition
import jinja2









  
def plotMap(data, opsName, opsColour):
    my_map=folium.Map(location=[15.185833, 69.112000], zoom_start=5)
    print("Inside plotMap")
    print(opsColour)
    for _,ap in data.iterrows() :
        folium.Marker(
            location=[ap['Lat'], ap['Long']],
            popup=(ap["Name "],ap["Pennant No."],ap["Country"],ap["Type"], ap["CLASS"],ap["Speed"],ap["Length"]),
            tooltip=(ap["Name "],ap["Pennant No."],ap["Country"],ap["Type"], ap["CLASS"],ap["Speed"],ap["Length"]),
            icon=folium.Icon(color=opsColour, icon="ship", prefix='fa'),
            #icon =folium.Icon(color=ships['colors'], prefix='fa', icon='ship')
     	    ).add_to(my_map)
        my_map.save(opsName + "map.html")   
    webbrowser.open(opsName + "map.html")

def plotCmdMap(data, opsName, opsColour):
    my_map=folium.Map(location=[15.185833, 69.112000], zoom_start=5)
    print("Inside plotCmdMap")
    print(opsColour)
    for _,ap in data.iterrows() :
        folium.Marker(
            location=[ap['Lat'], ap['Long']],
            popup=(ap["Name "],ap["Predicted_Score"]),
            tooltip=(ap["Name "],ap["Predicted_Score"]),
            icon=folium.Icon(color=opsColour, icon="ship", prefix='fa'),
            #icon =folium.Icon(color=ships['colors'], prefix='fa', icon='ship')
     	    ).add_to(my_map)
        my_map.save(opsName + "map.html")   
    webbrowser.open(opsName + "map.html")






#ships['colors'] = ships.apply(select_marker_color, axis=1)
#ships.head(3)

#my_map=folium.Map(
 #  location=[15.185833, 69.112000],
  #  zoom_start=5
   # )

#for _,ship in ships.iterrows():
#   folium.Marker(
 #       location=[ship['Lat'], ship['Long']],
  #      popup=ship["Name "],
   #     tooltip=ship["Name "],
    #    icon =folium.Icon(color=ship['colors'], prefix='fa', icon='ship')
   # ).add_to(my_map)
    
#my_map.save("map.html")
#webbrowser.open("map.html")
'''

formatter = "function(num) {return L.Util.formatNum(num, 3) + ' º ';};"

MousePosition(
    position="topright",
    separator=" | ",
    empty_string="NaN",
    lng_first=True,
    num_digits=20,
    prefix="Coordinates:",
    lat_formatter=formatter,
    lng_formatter=formatter,
).add_to(my_map)



#my_map.save("map.html")
#webbrowser.open("map.html")



#document.getElementById("latitude").value = e.latlng.lat.toFixed(4);
'''


